# -*- coding: utf-8 -*-
"""test_train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CC_kMK2qK5yZ7ZVKN8i_OWrUPT6ZzgnT
"""

# tests/test_train.py

import json
import os
import pytest
import pickle
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from src.train import load_config, train_model

CONFIG_PATH = "config/config.json"

def test_config_file_exists():
    assert os.path.exists(CONFIG_PATH), "Config file does not exist."

def test_config_structure():
    config = load_config(CONFIG_PATH)
    assert "C" in config and isinstance(config["C"], float)
    assert "solver" in config and isinstance(config["solver"], str)
    assert "max_iter" in config and isinstance(config["max_iter"], int)

def test_model_training():
    config = load_config(CONFIG_PATH)
    digits = load_digits()
    X, y = digits.data, digits.target

    model = train_model(X, y, config)
    assert isinstance(model, LogisticRegression)
    assert hasattr(model, "coef_")  # Checks if model has been fitted

def test_model_accuracy():
    config = load_config(CONFIG_PATH)
    digits = load_digits()
    X, y = digits.data, digits.target

    model = train_model(X, y, config)
    accuracy = model.score(X, y)
    assert accuracy > 0.8, f"Model accuracy too low: {accuracy}"

"""Now that we have created the necessary files and directories, you can run the test cell again."""

