# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/106RGY8SrRRB7eYtfn6eksdYmz96RVmvK
"""

# src/inference.py

import pickle
from sklearn.datasets import load_digits

def load_model(model_path='model_train.pkl'):
    with open(model_path, 'rb') as f:
        model = pickle.load(f)
    return model

def main():
    # Load data
    digits = load_digits()
    X = digits.data

    # Load model
    model = load_model()

    # Predict
    predictions = model.predict(X)

    # Print first 10 predictions as sample
    print("Sample predictions:", predictions[:10])

if __name__ == '__main__':
    main()



