# -*- coding: utf-8 -*-
"""train.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cfkJIDo_7JgiZzbyucU8wYFxoa0N1pjk
"""

import json
import pickle
from sklearn.datasets import load_digits
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split

def load_config(path='config/config.json'):
    with open(path, 'r') as f:
        return json.load(f)

def train_model(X, y, config):
    model = LogisticRegression(
        C=config['C'],
        solver=config['solver'],
        max_iter=config['max_iter']
    )
    model.fit(X, y)
    return model

def main():
    # Load data
    digits = load_digits()
    X, y = digits.data, digits.target

    # Load config
    config = load_config()

    # Train model
    model = train_model(X, y, config)

    # Save model
    with open('model_train.pkl', 'wb') as f:
        pickle.dump(model, f)

    print("✅ Model training complete and saved as model_train.pkl")

if __name__ == '__main__':
    main()
