# -*- coding: utf-8 -*-
"""utils.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OIF_wucerG66oYraqegvYihotV1y3BC5
"""

# src/utils.py

import json
import os

def load_config(config_path='config/config.json'):
    """
    Loads JSON configuration file from the given path.

    Args:
        config_path (str): Path to JSON config file.

    Returns:
        dict: Configuration parameters as a dictionary.
    """
    if not os.path.exists(config_path):
        raise FileNotFoundError(f"Config file not found: {config_path}")

    with open(config_path, 'r') as f:
        config = json.load(f)
    return config